import * as vscode from 'vscode';

const messages = {
  en: {
    auto: 'Auto',
    redetect: 'Re-detect PHP versions',
    settings: 'Open workspace settings',
    detectedFrom: 'Detected from {0}',
    noWorkspace: 'Open a workspace folder to use SoPHP.',
    indexed: 'Indexed {0} PHP files.',
    renamePrompt: 'New name for {0}',
    safeRenameUnavailable: 'SoPHP previewed Rename requires the SoPHP PHP language server.',
    addParameterName: 'New parameter name (without $)',
    addParameterType: 'Parameter type (int, string, bool, float)',
    addParameterValue: 'Literal value to pass at existing calls',
    addParameterUnavailable: 'SoPHP could not prove a complete editable method family and its supported calls.',
    removeParameterUnavailable: 'SoPHP could not prove that this parameter and its supported calls can be removed safely.',
    reorderParameterUnavailable: 'SoPHP could not prove that these parameters and calls can be reordered safely.',
    reorderParameterCurrent: 'current position',
    reorderParameterTarget: 'Move the selected parameter to this position',
    addParameterWorkspaceScope: 'This preview covers indexed workspace declarations and calls. Uses outside the workspace will not be changed.',
    applyPreviewedRename: 'Apply the previewed Rename to {0}?',
    renameFailed: 'SoPHP rename failed: {0}',
    renameSnapshotsMissing: 'Rename omitted source snapshots. Run Rename again.',
    renameSnapshotMissing: 'Rename omitted a source snapshot. Run Rename again.',
    renameSourceChanged: 'A PHP file changed while Rename edits were being prepared. Run Rename again.',
    renameDocumentChangedPrepare: 'The PHP document changed while Rename was being prepared. Run Rename again.',
    renameDocumentChangedEdits: 'A PHP document changed while Rename edits were being prepared. Run Rename again.',
    renameDocumentChangedVerify: 'A PHP document changed while Rename edits were being verified. Run Rename again.',
    renamePlanUnverified: 'SoPHP could not verify the Rename plan. Run Rename again.',
    renamePreviewClosed: 'A Rename preview was closed before confirmation. Run Rename again.',
    renameDiskChanged: 'A PHP file changed on disk during Rename preview. Run Rename again.',
    renameApplyFailed: 'SoPHP could not apply Rename changes. Run Rename again.',
    invalidName: 'Enter a valid PHP class-like name.',
    conflict: 'The target file already exists: {0}',
    duplicate: 'Cannot safely rename duplicate symbol: {0}',
    syntaxError: 'Cannot safely rename because a related PHP file contains syntax errors: {0}',
    pasteImports: 'Paste with PHP imports',
    reportTitle: 'SoPHP Compatibility Report',
    noType: 'SoPHP: No PHP type found in the active file.',
    namespacePath: 'Namespace should be {0} for this PSR-4 path.',
    globalNamespace: '(global)',
    primaryTypeFilename: 'Primary type name should match {0}.php.',
    renameFile: 'Rename file to {0}.php',
    changeNamespace: 'Change namespace to match PSR-4 path',
    createNoWorkspace: 'SoPHP: Open a workspace folder first.',
    createOutsidePsr4: 'SoPHP: The target directory is not covered by Composer PSR-4 autoloading.',
    createOutsideProject: 'SoPHP: Choose a test directory in the current Composer project.',
    createNotDirectory: 'SoPHP: The selected test destination is unavailable or is not a directory.',
    createInvalidNamespace: 'SoPHP: The Composer PSR-4 path cannot form a valid PHP namespace.',
    createChangedProject: 'SoPHP: Composer configuration changed while reviewing the new file. Run the command again.',
    createChangedDirectory: 'SoPHP: The target directory changed while reviewing the new file. Run the command again.',
    createChangedVersion: 'SoPHP: The target PHP version changed while reviewing the new file. Run the command again.',
    enumPhpTarget: 'SoPHP: Enums require PHP 8.1 or later (target: {0}).',
    newTypeName: 'New PHP {0} name',
    kindClass: 'class',
    kindAbstractClass: 'abstract class',
    kindInterface: 'interface',
    kindTrait: 'trait',
    kindEnum: 'enum',
    kindTest: 'test',
    validTypeName: 'Enter a valid PHP type name.',
    fileExists: 'SoPHP: {0} already exists.',
    createTypeConfirm: 'Create {0} at {1}?',
    chooseTestDirectory: 'Choose a Composer test directory',
    createApplyFailed: 'VS Code could not create the PHP file.',
    createPreviewCloseFailed: 'VS Code could not close the PHP preview. The file was not created.',
    createPreviewFailed: 'VS Code could not finish the PHP preview: {0}',
    createOpenFailed: 'The PHP file was created, but VS Code could not open it: {0}',
    appliedOpenFailed: 'Changes were applied, but VS Code could not open the result: {0}',
    create: 'Create',
    indexingWorkspace: 'SoPHP: Indexing workspace…',
    indexingComposerProject: 'SoPHP: Indexing Composer project…',
    keptIntelephense: 'SoPHP kept Intelephense as the PHP language provider. Set phpCompanion.languageServer.enabled explicitly to change this choice.',
    cliRuntimeUnknown: 'CLI runtime extensions: unknown or target-version mismatch',
    showSymfony: 'Show SoPHP Symfony',
    symfonyRecommendation: 'This Symfony project needs SoPHP Symfony for precise services, routes, events, and Controller-to-Twig support.',
    languageServerFailed: 'SoPHP language server failed to start. See the SoPHP output channel.',
    definitionLookingUp: 'SoPHP: Looking up definition…',
    definitionNotFound: 'SoPHP: No definition available yet; indexing may still be running.',
    experimentalRequired: 'Enable phpCompanion.experimental.refactoring to use project-wide indexing and refactoring.',
    indexingDisabled: 'SoPHP indexing is disabled.',
    moveHere: 'Move PHP File Here',
    safeMoveIndexingMode: 'Safe Move requires phpCompanion.indexing.mode to be onDemand, progressive, or experimental.',
    safeMoveWillUpdate: 'Safe Move will update the PHP namespace and proven references.',
    preview: 'Preview',
    apply: 'Apply',
    applyPreviewedSafeMove: 'Apply the previewed Safe Move?',
    safeMoveDiff: 'Safe Move: {0}',
    extractDiff: '{0}: {1}',
    applyPreviewedExtract: 'Apply the previewed {0}?',
    previewClosed: 'A preview was closed before confirmation. Run the action again.',
    extractCancelled: 'The source or target changed. Run the refactoring again.',
    extractApplyFailed: 'VS Code could not apply the refactoring.',
    moveFileLabel: 'Move {0}',
    safeMoveApplyFailed: 'VS Code could not move the PHP file and update its references.',
    safeMoveFailed: 'Safe Move failed: {0}',
    safeMoveIndexRefreshFailed: 'File moved, but the project index could not be refreshed: {0}',
    selectImport: 'Select import for {0}',
    importClassIndexingMode: 'SoPHP Import Class requires indexing.mode to be onDemand, progressive, or experimental.',
    noUniqueComposerCandidate: 'No unique Composer candidate found for {0}.',
    selectClassImport: 'Select the class to import for {0}',
    chooseAlias: 'Choose an alias for {0}',
    validIdentifier: 'Enter a valid PHP identifier.',
    importCancelled: 'Import cancelled because the PHP document changed.',
    importApplyFailed: 'VS Code could not apply the PHP import. Run the command again.',
    cannotImportSyntax: 'Cannot import into a PHP file with syntax errors.',
    noComposerPsr4Candidate: 'No Composer PSR-4 candidate found for {0}.',
    optimizeIndexRequired: 'SoPHP Optimize Imports requires project indexing.',
    importsAlreadyOrganized: 'PHP imports are already organized or cannot be changed safely.',
    optimizeImports: 'Optimize imports.',
    applyPreviewedImportChanges: 'Apply the previewed import changes?',
    optimizeCancelled: 'Optimize Imports cancelled because the document changed.',
    optimizeApplyFailed: 'VS Code could not apply Optimize Imports. Run the command again.',
    cannotOptimizeSyntax: 'Cannot optimize imports in a PHP file with syntax errors.',
    importsAlreadyOptimized: 'PHP imports are already optimized or cannot be changed safely.',
    optimizeRemoved: 'Optimize imports ({0} removed).',
    optimizeDiff: 'Optimize Imports: {0}',
    diagnosticsTitle: '# SoPHP diagnostics',
    activationRegistration: '- Activation registration: {0} ms',
    experimentalIndexLoaded: '- Experimental index loaded: {0}',
    yes: 'yes',
    no: 'no',
    reportRuntime: '  - Runtime: {0}',
    runtimeDetails: 'PHP {0} {1} via {2}; {3} loaded extensions',
    runtimeUnknown: 'unknown or target-version mismatch',
    psr4Mappings: '  - PSR-4 mappings: {0}',
    cliRuntimeDetails: 'CLI {0} ({1}), {2} extensions — {3}',
    moveValidNamespace: 'Safe Move requires one valid namespace declaration.',
    moveAmbiguousNamespace: 'Safe Move namespace mapping is ambiguous.',
    languageServerUnavailable: 'SoPHP Language Server is unavailable.',
    movePlanIncomplete: 'SoPHP Language Server did not return a complete Safe Move edit.',
    moveParticipantsChanged: 'Safe Move participants changed during planning. Retry the move.',
    moveReconciliationIncomplete: 'SoPHP Language Server did not return a Safe Move reconciliation edit.',
    moveSnapshotChanged: 'Safe Move snapshot changed for {0}; replanning.',
    moveUpdateFailed: 'VS Code could not update moved PHP namespaces and references.',
    movedFileInvalid: 'Moved file {0} failed namespace or syntax validation.',
    moveEditsRemaining: 'Safe Move still requires {0} reconciliation edit group(s).',
    moveRollbackUnavailable: 'Cannot roll back Safe Move because {0} is unavailable.',
    moveRollbackExists: 'Cannot roll back Safe Move because {0} already exists.',
    moveRollbackFailed: 'VS Code could not roll back the unplanned Safe Move.',
    moveReconciliationLost: 'SoPHP Language Server did not retain a Safe Move reconciliation plan.',
    renameIndexingMode: 'SoPHP Rename requires indexing.mode to be onDemand, progressive, or experimental.',
    composerProjectRequired: 'The files are not covered by a Composer PSR-4 project.',
    indexLimit: 'Index limit exceeded ({0} files). Narrow phpCompanion.files.exclude or raise indexing.maxFiles.',
  },
  zh: {
    auto: '自动检测',
    redetect: '重新检测 PHP 版本',
    settings: '打开工作区设置',
    detectedFrom: '检测来源：{0}',
    noWorkspace: '请先打开工作区目录再使用 SoPHP。',
    indexed: '已索引 {0} 个 PHP 文件。',
    renamePrompt: '输入 {0} 的新名称',
    safeRenameUnavailable: '预览式重命名需要启用 SoPHP PHP 语言服务器。',
    addParameterName: '新参数名称（不含 $）',
    addParameterType: '参数类型（int、string、bool、float）',
    addParameterValue: '现有调用传入的字面量值',
    addParameterUnavailable: 'SoPHP 无法证明方法家族及其受支持调用都可安全编辑。',
    removeParameterUnavailable: 'SoPHP 无法证明此参数及其受支持调用可安全删除。',
    reorderParameterUnavailable: 'SoPHP 无法证明这些参数及调用可安全重排。',
    reorderParameterCurrent: '当前位置',
    reorderParameterTarget: '将选中的参数移到这个位置',
    addParameterWorkspaceScope: '此预览只覆盖已索引工作区中的声明和调用；工作区外的使用不会被修改。',
    applyPreviewedRename: '应用预览中的重命名，将名称改为 {0}？',
    renameFailed: 'SoPHP 重命名失败：{0}',
    renameSnapshotsMissing: '重命名计划缺少源文件快照，请重新运行重命名。',
    renameSnapshotMissing: '重命名计划缺少一个源文件快照，请重新运行重命名。',
    renameSourceChanged: '准备重命名编辑期间有 PHP 文件发生变化，请重新运行重命名。',
    renameDocumentChangedPrepare: '准备重命名期间 PHP 文档发生变化，请重新运行重命名。',
    renameDocumentChangedEdits: '准备重命名编辑期间 PHP 文档发生变化，请重新运行重命名。',
    renameDocumentChangedVerify: '验证重命名编辑期间 PHP 文档发生变化，请重新运行重命名。',
    renamePlanUnverified: 'SoPHP 无法验证重命名计划，请重新运行重命名。',
    renamePreviewClosed: '确认前关闭了重命名预览，请重新运行重命名。',
    renameDiskChanged: '查看重命名预览期间磁盘上的 PHP 文件发生变化，请重新运行重命名。',
    renameApplyFailed: 'SoPHP 无法应用重命名修改，请重新运行重命名。',
    invalidName: '请输入有效的 PHP 类名称。',
    conflict: '目标文件已经存在：{0}',
    duplicate: '存在重复符号，无法安全重命名：{0}',
    syntaxError: '相关 PHP 文件包含语法错误，无法安全重命名：{0}',
    pasteImports: '粘贴并添加 PHP import',
    reportTitle: 'SoPHP 兼容性报告',
    noType: 'SoPHP：当前文件中没有找到 PHP 类型。',
    namespacePath: '此 PSR-4 路径的命名空间应为 {0}。',
    globalNamespace: '全局命名空间',
    primaryTypeFilename: '主类型名称应与 {0}.php 匹配。',
    renameFile: '将文件重命名为 {0}.php',
    changeNamespace: '将命名空间改为与 PSR-4 路径匹配',
    createNoWorkspace: 'SoPHP：请先打开工作区目录。',
    createOutsidePsr4: 'SoPHP：目标目录不在 Composer PSR-4 自动加载范围内。',
    createOutsideProject: 'SoPHP：请选择当前 Composer 项目内的测试目录。',
    createNotDirectory: 'SoPHP：选中的测试目标已不可用或不是目录。',
    createInvalidNamespace: 'SoPHP：Composer PSR-4 路径无法组成有效的 PHP 命名空间。',
    createChangedProject: 'SoPHP：预览期间 Composer 配置发生变化，请重新执行命令。',
    createChangedDirectory: 'SoPHP：预览期间目标目录发生变化，请重新执行命令。',
    createChangedVersion: 'SoPHP：预览期间目标 PHP 版本发生变化，请重新执行命令。',
    enumPhpTarget: 'SoPHP：Enum 需要 PHP 8.1 或更新版本（目标版本：{0}）。',
    newTypeName: '新建 PHP {0}名称',
    kindClass: '类',
    kindAbstractClass: '抽象类',
    kindInterface: '接口',
    kindTrait: 'Trait',
    kindEnum: 'Enum',
    kindTest: '测试类',
    validTypeName: '请输入有效的 PHP 类型名称。',
    fileExists: 'SoPHP：{0} 已存在。',
    createTypeConfirm: '在 {1} 创建 {0}？',
    chooseTestDirectory: '选择 Composer 测试目录',
    createApplyFailed: 'VS Code 无法创建 PHP 文件。',
    createPreviewCloseFailed: 'VS Code 无法关闭 PHP 预览，文件未创建。',
    createPreviewFailed: 'VS Code 无法完成 PHP 预览：{0}',
    createOpenFailed: 'PHP 文件已创建，但 VS Code 无法打开它：{0}',
    appliedOpenFailed: '改动已应用，但 VS Code 无法打开结果：{0}',
    create: '创建',
    indexingWorkspace: 'SoPHP：正在索引工作区…',
    indexingComposerProject: 'SoPHP：正在索引 Composer 项目…',
    keptIntelephense: 'SoPHP 已保留 Intelephense 作为 PHP 语言提供器。若要更改，请显式设置 phpCompanion.languageServer.enabled。',
    cliRuntimeUnknown: 'CLI 运行时扩展：未知或与目标 PHP 版本不匹配',
    showSymfony: '查看 SoPHP Symfony',
    symfonyRecommendation: '此 Symfony 项目需要 SoPHP Symfony，才能获得精确的服务、路由、事件及 Controller 到 Twig 支持。',
    languageServerFailed: 'SoPHP 语言服务器启动失败。请查看 SoPHP 输出通道。',
    definitionLookingUp: 'SoPHP：正在查找定义…',
    definitionNotFound: 'SoPHP：暂未找到定义；索引可能仍在进行。',
    experimentalRequired: '启用 phpCompanion.experimental.refactoring 才能使用项目范围索引和重构。',
    indexingDisabled: 'SoPHP 索引已关闭。',
    moveHere: '将 PHP 文件移到此处',
    safeMoveIndexingMode: '安全移动要求 phpCompanion.indexing.mode 为 onDemand、progressive 或 experimental。',
    safeMoveWillUpdate: '安全移动将更新 PHP 命名空间及已证明的引用。',
    preview: '预览',
    apply: '应用',
    applyPreviewedSafeMove: '应用预览中的安全移动？',
    safeMoveDiff: '安全移动：{0}',
    extractDiff: '{0}：{1}',
    applyPreviewedExtract: '应用预览中的{0}？',
    previewClosed: '确认前已有预览被关闭，请重新执行操作。',
    extractCancelled: '源文件或目标文件已变化，请重新运行重构。',
    extractApplyFailed: 'VS Code 无法应用此重构。',
    moveFileLabel: '移动 {0}',
    safeMoveApplyFailed: 'VS Code 无法移动 PHP 文件并更新其引用。',
    safeMoveFailed: '安全移动失败：{0}',
    safeMoveIndexRefreshFailed: '文件已移动，但无法刷新项目索引：{0}',
    selectImport: '为 {0} 选择导入项',
    importClassIndexingMode: 'SoPHP 导入类要求 indexing.mode 为 onDemand、progressive 或 experimental。',
    noUniqueComposerCandidate: '找不到 {0} 唯一的 Composer 候选项。',
    selectClassImport: '选择要为 {0} 导入的类',
    chooseAlias: '为 {0} 选择别名',
    validIdentifier: '请输入有效的 PHP 标识符。',
    importCancelled: 'PHP 文档发生变化，已取消导入。',
    importApplyFailed: 'VS Code 无法应用 PHP 导入，请重新执行命令。',
    cannotImportSyntax: 'PHP 文件存在语法错误，无法导入。',
    noComposerPsr4Candidate: '找不到 {0} 的 Composer PSR-4 候选项。',
    optimizeIndexRequired: 'SoPHP 优化导入要求启用项目索引。',
    importsAlreadyOrganized: 'PHP 导入已整理，或无法安全更改。',
    optimizeImports: '优化导入。',
    applyPreviewedImportChanges: '应用预览中的导入变更？',
    optimizeCancelled: '文档发生变化，已取消优化导入。',
    optimizeApplyFailed: 'VS Code 无法应用导入优化，请重新执行命令。',
    cannotOptimizeSyntax: 'PHP 文件存在语法错误，无法优化导入。',
    importsAlreadyOptimized: 'PHP 导入已优化，或无法安全更改。',
    optimizeRemoved: '优化导入（移除 {0} 项）。',
    optimizeDiff: '优化导入：{0}',
    diagnosticsTitle: '# SoPHP 诊断信息',
    activationRegistration: '- 扩展激活注册：{0} 毫秒',
    experimentalIndexLoaded: '- 实验性索引已加载：{0}',
    yes: '是',
    no: '否',
    reportRuntime: '  - 运行时：{0}',
    runtimeDetails: 'PHP {0} {1}，路径 {2}；已加载 {3} 个扩展',
    runtimeUnknown: '未知或与目标版本不匹配',
    psr4Mappings: '  - PSR-4 映射：{0}',
    cliRuntimeDetails: 'CLI {0}（{1}），{2} 个扩展 — {3}',
    moveValidNamespace: '安全移动要求文件只有一个有效的命名空间声明。',
    moveAmbiguousNamespace: '安全移动的命名空间映射存在歧义。',
    languageServerUnavailable: 'SoPHP 语言服务器不可用。',
    movePlanIncomplete: 'SoPHP 语言服务器未返回完整的安全移动编辑计划。',
    moveParticipantsChanged: '规划期间参与安全移动的文件已变化，请重试。',
    moveReconciliationIncomplete: 'SoPHP 语言服务器未返回安全移动协调编辑。',
    moveSnapshotChanged: '{0} 的安全移动快照已变化，正在重新规划。',
    moveUpdateFailed: 'VS Code 无法更新已移动 PHP 文件的命名空间和引用。',
    movedFileInvalid: '已移动文件 {0} 未通过命名空间或语法校验。',
    moveEditsRemaining: '安全移动仍需要 {0} 组协调编辑。',
    moveRollbackUnavailable: '无法回滚安全移动：{0} 不可用。',
    moveRollbackExists: '无法回滚安全移动：{0} 已存在。',
    moveRollbackFailed: 'VS Code 无法回滚未规划的安全移动。',
    moveReconciliationLost: 'SoPHP 语言服务器未保留安全移动协调计划。',
    renameIndexingMode: 'SoPHP 重命名要求 indexing.mode 为 onDemand、progressive 或 experimental。',
    composerProjectRequired: '这些文件不属于 Composer PSR-4 项目。',
    indexLimit: '索引数量超过上限（{0} 个文件）。请缩小 phpCompanion.files.exclude 范围或提高 indexing.maxFiles。',
  },
} as const;

type MessageKey = keyof typeof messages.en;

export function t(key: MessageKey, ...args: string[]): string {
  const language = vscode.env.language.toLowerCase().startsWith('zh') ? messages.zh : messages.en;
  return args.reduce((value, argument, index) => value.replace(`{${index}}`, argument), language[key] as string);
}
