// Generated from JetBrains/phpstorm-stubs at e4f5f6c3de39f3bab3e9f3fca4b8cdb8b061e681, gd/gd.php.
// Apache-2.0. See THIRD_PARTY_NOTICES.md. Runtime signatures and availability are audited separately.
export const GD_FUNCTIONS = [
  "gd_info",
  "imagearc",
  "imageellipse",
  "imagechar",
  "imagecharup",
  "imagecolorat",
  "imagecolorallocate",
  "imagepalettecopy",
  "imagecreatefromstring",
  "imagecolorclosest",
  "imagecolorclosesthwb",
  "imagecolordeallocate",
  "imagecolorresolve",
  "imagecolorexact",
  "imagecolorset",
  "imagecolortransparent",
  "imagecolorstotal",
  "imagecolorsforindex",
  "imagecopy",
  "imagecopymerge",
  "imagecopymergegray",
  "imagecopyresized",
  "imagecreate",
  "imagecreatetruecolor",
  "imageistruecolor",
  "imagetruecolortopalette",
  "imagesetthickness",
  "imagefilledarc",
  "imagefilledellipse",
  "imagealphablending",
  "imagesavealpha",
  "imagecolorallocatealpha",
  "imagecolorresolvealpha",
  "imagecolorclosestalpha",
  "imagecolorexactalpha",
  "imagecopyresampled",
  "imagerotate",
  "imageantialias",
  "imagesettile",
  "imagesetbrush",
  "imagesetstyle",
  "imagecreatefrompng",
  "imagecreatefromavif",
  "imagecreatefromgif",
  "imagecreatefromjpeg",
  "imagecreatefromwbmp",
  "imagecreatefromwebp",
  "imagecreatefromxbm",
  "imagecreatefromxpm",
  "imagecreatefromgd",
  "imagecreatefromgd2",
  "imagecreatefromgd2part",
  "imagepng",
  "imagewebp",
  "imagegif",
  "imagejpeg",
  "imagewbmp",
  "imagegd",
  "imagegd2",
  "imagedestroy",
  "imagegammacorrect",
  "imagefill",
  "imagefilledpolygon",
  "imagefilledrectangle",
  "imagefilltoborder",
  "imagefontwidth",
  "imagefontheight",
  "imageinterlace",
  "imageline",
  "imageloadfont",
  "imagepolygon",
  "imagerectangle",
  "imagesetpixel",
  "imagestring",
  "imagestringup",
  "imagesx",
  "imagesy",
  "imagedashedline",
  "imagettfbbox",
  "imagettftext",
  "imageftbbox",
  "imagefttext",
  "imagetypes",
  "jpeg2wbmp",
  "png2wbmp",
  "image2wbmp",
  "imagelayereffect",
  "imagecolormatch",
  "imagexbm",
  "imagefilter",
  "imageconvolution",
  "imageresolution",
  "imagesetclip",
  "imagegetclip",
  "imageopenpolygon",
  "imagecreatefrombmp",
  "imagebmp",
  "imagecreatefromtga",
  "imagegetinterpolation",
  "imageavif",
  "imageaffine",
  "imageaffinematrixconcat",
  "imageaffinematrixget",
  "imagecrop",
  "imagecropauto",
  "imageflip",
  "imagepalettetotruecolor",
  "imagescale",
  "imagesetinterpolation"
] as const;
export const GD_CONSTANT_NAMES = [
  "GD_BUNDLED",
  "GD_EXTRA_VERSION",
  "GD_MAJOR_VERSION",
  "GD_MINOR_VERSION",
  "GD_RELEASE_VERSION",
  "GD_VERSION",
  "IMG_AFFINE_ROTATE",
  "IMG_AFFINE_SCALE",
  "IMG_AFFINE_SHEAR_HORIZONTAL",
  "IMG_AFFINE_SHEAR_VERTICAL",
  "IMG_AFFINE_TRANSLATE",
  "IMG_ARC_CHORD",
  "IMG_ARC_EDGED",
  "IMG_ARC_NOFILL",
  "IMG_ARC_PIE",
  "IMG_ARC_ROUNDED",
  "IMG_AVIF",
  "IMG_BELL",
  "IMG_BESSEL",
  "IMG_BICUBIC",
  "IMG_BICUBIC_FIXED",
  "IMG_BILINEAR_FIXED",
  "IMG_BLACKMAN",
  "IMG_BMP",
  "IMG_BOX",
  "IMG_BSPLINE",
  "IMG_CATMULLROM",
  "IMG_COLOR_BRUSHED",
  "IMG_COLOR_STYLED",
  "IMG_COLOR_STYLEDBRUSHED",
  "IMG_COLOR_TILED",
  "IMG_COLOR_TRANSPARENT",
  "IMG_CROP_BLACK",
  "IMG_CROP_DEFAULT",
  "IMG_CROP_SIDES",
  "IMG_CROP_THRESHOLD",
  "IMG_CROP_TRANSPARENT",
  "IMG_CROP_WHITE",
  "IMG_EFFECT_ALPHABLEND",
  "IMG_EFFECT_MULTIPLY",
  "IMG_EFFECT_NORMAL",
  "IMG_EFFECT_OVERLAY",
  "IMG_EFFECT_REPLACE",
  "IMG_FILTER_BRIGHTNESS",
  "IMG_FILTER_COLORIZE",
  "IMG_FILTER_CONTRAST",
  "IMG_FILTER_EDGEDETECT",
  "IMG_FILTER_EMBOSS",
  "IMG_FILTER_GAUSSIAN_BLUR",
  "IMG_FILTER_GRAYSCALE",
  "IMG_FILTER_MEAN_REMOVAL",
  "IMG_FILTER_NEGATE",
  "IMG_FILTER_PIXELATE",
  "IMG_FILTER_SCATTER",
  "IMG_FILTER_SELECTIVE_BLUR",
  "IMG_FILTER_SMOOTH",
  "IMG_FLIP_BOTH",
  "IMG_FLIP_HORIZONTAL",
  "IMG_FLIP_VERTICAL",
  "IMG_GAUSSIAN",
  "IMG_GD2_COMPRESSED",
  "IMG_GD2_RAW",
  "IMG_GENERALIZED_CUBIC",
  "IMG_GIF",
  "IMG_HAMMING",
  "IMG_HANNING",
  "IMG_HERMITE",
  "IMG_JPEG",
  "IMG_JPG",
  "IMG_MITCHELL",
  "IMG_NEAREST_NEIGHBOUR",
  "IMG_PNG",
  "IMG_POWER",
  "IMG_QUADRATIC",
  "IMG_SINC",
  "IMG_TGA",
  "IMG_TRIANGLE",
  "IMG_WBMP",
  "IMG_WEBP",
  "IMG_WEBP_LOSSLESS",
  "IMG_WEIGHTED4",
  "IMG_XPM",
  "PNG_ALL_FILTERS",
  "PNG_FILTER_AVG",
  "PNG_FILTER_NONE",
  "PNG_FILTER_PAETH",
  "PNG_FILTER_SUB",
  "PNG_FILTER_UP",
  "PNG_NO_FILTER"
] as const;
export const GD_SELECTED_CONSTANTS = {
  "IMG_GIF": 1,
  "IMG_JPG": 2,
  "IMG_JPEG": 2,
  "IMG_PNG": 4,
  "IMG_WEBP": 32,
  "IMG_BMP": 64,
  "IMG_TGA": 128,
  "IMG_AVIF": 256,
  "IMG_GD2_RAW": 1,
  "IMG_GD2_COMPRESSED": 2,
  "IMG_FILTER_NEGATE": 0,
  "IMG_FILTER_GRAYSCALE": 1,
  "IMG_FILTER_BRIGHTNESS": 2,
  "IMG_FILTER_CONTRAST": 3,
  "IMG_FILTER_COLORIZE": 4,
  "IMG_FILTER_GAUSSIAN_BLUR": 7,
  "IMG_CROP_DEFAULT": 0,
  "IMG_CROP_TRANSPARENT": 1,
  "IMG_CROP_BLACK": 2,
  "IMG_CROP_WHITE": 3,
  "IMG_CROP_SIDES": 4,
  "IMG_CROP_THRESHOLD": 5,
  "IMG_FLIP_HORIZONTAL": 1,
  "IMG_FLIP_VERTICAL": 2,
  "IMG_FLIP_BOTH": 3,
  "IMG_BILINEAR_FIXED": 3,
  "IMG_ARC_PIE": 0,
  "IMG_ARC_CHORD": 1,
  "IMG_FILTER_EDGEDETECT": 5,
  "IMG_FILTER_SELECTIVE_BLUR": 8,
  "IMG_FILTER_EMBOSS": 6,
  "IMG_FILTER_MEAN_REMOVAL": 9,
  "IMG_FILTER_SMOOTH": 10,
  "IMG_FILTER_PIXELATE": 11,
  "IMG_FILTER_SCATTER": 12,
  "IMG_EFFECT_REPLACE": 0,
  "IMG_EFFECT_ALPHABLEND": 1,
  "IMG_EFFECT_NORMAL": 2,
  "IMG_EFFECT_OVERLAY": 3,
  "IMG_EFFECT_MULTIPLY": 4,
  "IMG_COLOR_TILED": -5,
  "IMG_COLOR_STYLED": -2,
  "IMG_COLOR_BRUSHED": -3,
  "IMG_COLOR_STYLEDBRUSHED": -4,
  "IMG_COLOR_TRANSPARENT": -6,
  "IMG_AFFINE_TRANSLATE": 0,
  "IMG_AFFINE_SCALE": 1,
  "IMG_AFFINE_ROTATE": 2,
  "IMG_AFFINE_SHEAR_HORIZONTAL": 3,
  "IMG_AFFINE_SHEAR_VERTICAL": 4
} as const;
