// Old parameter names from local PHP 7.2 and 7.4 Sockets reflection.
export const SOCKETS_PHP7_PARAMETER_NAMES: Readonly<Record<string, readonly string[]>> = {
  "socket_select": ["read_fds","write_fds","except_fds","tv_sec","tv_usec"],
  "socket_create_pair": ["domain","type","protocol","fd"],
  "socket_write": ["socket","buf","length"],
  "socket_read": ["socket","length","type"],
  "socket_getsockname": ["socket","addr","port"],
  "socket_getpeername": ["socket","addr","port"],
  "socket_connect": ["socket","addr","port"],
  "socket_strerror": ["errno"],
  "socket_bind": ["socket","addr","port"],
  "socket_recv": ["socket","buf","len","flags"],
  "socket_send": ["socket","buf","len","flags"],
  "socket_recvfrom": ["socket","buf","len","flags","name","port"],
  "socket_sendto": ["socket","buf","len","flags","addr","port"],
  "socket_get_option": ["socket","level","optname"],
  "socket_set_option": ["socket","level","optname","optval"],
  "socket_shutdown": ["socket","how"],
  "socket_sendmsg": ["socket","msghdr","flags"],
  "socket_recvmsg": ["socket","msghdr","flags"],
  "socket_addrinfo_connect": ["addr"],
  "socket_addrinfo_bind": ["addr"],
  "socket_addrinfo_explain": ["addr"],
  "socket_getopt": ["socket","level","optname"],
  "socket_setopt": ["socket","level","optname","optval"],
};
