// Names checked against JetBrains/phpstorm-stubs at e4f5f6c3de39f3bab3e9f3fca4b8cdb8b061e681, standard/standard_8.php and standard/standard_9.php.
// Constant names and values checked against PHP 7.2 and 8.5 reflection. Apache-2.0; see THIRD_PARTY_NOTICES.md.
export const STANDARD_ARRAY_FUNCTIONS = [
  "krsort",
  "ksort",
  "natsort",
  "natcasesort",
  "asort",
  "arsort",
  "rsort",
  "end",
  "prev",
  "next",
  "reset",
  "current",
  "pos",
  "key",
  "extract",
  "compact",
  "range",
  "array_multisort",
  "array_merge_recursive",
  "array_replace_recursive",
  "array_count_values",
  "array_pad",
  "array_change_key_case",
  "array_intersect_ukey",
  "array_uintersect",
  "array_intersect_assoc",
  "array_uintersect_assoc",
  "array_intersect_uassoc",
  "array_uintersect_uassoc",
  "array_diff_ukey",
  "array_udiff",
  "array_diff_assoc",
  "array_diff_uassoc",
  "array_udiff_assoc",
  "array_udiff_uassoc"
] as const;
export const STANDARD_ARRAY_CONSTANTS = {
  "EXTR_OVERWRITE": 0,
  "EXTR_SKIP": 1,
  "EXTR_PREFIX_SAME": 2,
  "EXTR_PREFIX_ALL": 3,
  "EXTR_PREFIX_INVALID": 4,
  "EXTR_PREFIX_IF_EXISTS": 5,
  "EXTR_IF_EXISTS": 6,
  "EXTR_REFS": 256,
  "SORT_ASC": 4,
  "SORT_DESC": 3,
  "SORT_REGULAR": 0,
  "SORT_NUMERIC": 1,
  "SORT_STRING": 2,
  "SORT_LOCALE_STRING": 5,
  "SORT_NATURAL": 6,
  "SORT_FLAG_CASE": 8,
  "CASE_LOWER": 0,
  "CASE_UPPER": 1,
  "COUNT_NORMAL": 0,
  "COUNT_RECURSIVE": 1,
  "ARRAY_FILTER_USE_BOTH": 1,
  "ARRAY_FILTER_USE_KEY": 2
} as const;
