// Audited against JetBrains/phpstorm-stubs e4f5f6c3de39f3bab3e9f3fca4b8cdb8b061e681, tokenizer/.
// Apache-2.0. See THIRD_PARTY_NOTICES.md. Descriptive upstream text is omitted.
import type { SupportedPhpVersion } from './index.js';
import { TOKENIZER_KNOWN_CONSTANT_NAMES } from './tokenizer-catalog.js';

export interface TokenizerRuntimeFacts { constants: Record<string, number> }

const knownTokenConstants = new Set<string>(TOKENIZER_KNOWN_CONSTANT_NAMES);

export function normalizeTokenizerRuntimeFacts(value: unknown): TokenizerRuntimeFacts | undefined {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return undefined;
  const candidate = value as Record<string, unknown>;
  if (Object.keys(candidate).some((key) => key !== 'constants')) return undefined;
  const constants = candidate.constants;
  if (!constants || typeof constants !== 'object' || Array.isArray(constants)) return undefined;
  const entries = Object.entries(constants);
  if (!entries.length || entries.length > TOKENIZER_KNOWN_CONSTANT_NAMES.length
    || entries.some(([name, number]) => !knownTokenConstants.has(name)
      || typeof number !== 'number' || !Number.isSafeInteger(number) || number < 256 || number > 65_535)) return undefined;
  return { constants: Object.fromEntries(entries.sort(([left], [right]) => left.localeCompare(right))) };
}

export function auditedTokenizerStub(version: SupportedPhpVersion, runtime?: TokenizerRuntimeFacts): string {
  const php80 = Number(version.replace('.', '')) >= 80;
  const functions = php80
    ? `
/** @return list<array{int,string,int}|string> */ function token_get_all(string $code, int $flags = 0): array {}
function token_name(int $id): string {}
`
    : `
/** @return list<array{int,string,int}|string> */ function token_get_all($source, $flags = 0) {}
/** @return string */ function token_name($token) {}
`;
  const tokenClass = php80 ? `
class PhpToken implements Stringable {
  public int $id;
  public string $text;
  public int $line;
  public int $pos;
  final public function __construct(int $id, string $text, int $line = -1, int $pos = -1) {}
  /** @return list<static> */ public static function tokenize(string $code, int $flags = 0): array {}
  /** @param int|string|array<int|string> $kind */ public function is($kind): bool {}
  public function isIgnorable(): bool {}
  public function getTokenName(): ?string {}
  public function __toString(): string {}
}
` : '';
  // T_* values are generated by PHP's parser and are not stable across minor versions.
  const constants = Object.entries(normalizeTokenizerRuntimeFacts(runtime)?.constants ?? {})
    .map(([name, value]) => `const ${name} = ${value};`).join('\n');
  return `const TOKEN_PARSE = 1;\n${constants ? `${constants}\n` : ''}${functions}${tokenClass}`;
}
